source ~/.bash/aliases
source ~/.bash/gettext
source ~/.bash/anaconda
source ~/.bash/java

if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  GIT_PROMPT_ONLY_IN_REPO=0
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi

export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"

#iterm 2 escape code for color preset
echo -e "\033]1337;SetColors=preset=Pastel (Dark Background)\a"

#remove dups in the command line history
export HISTCONTROL=erasedups
export HISTSIZE=10000

export OSXDEVSETUP_HOME=~/.osxdevsetup
shopt -s histappend
export PATH
